version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php app.php"
  relay: pipes

websockets:
  broker: default
  allowed_origin: "*"
  path: "/ws"

broadcast:
  default:
    driver: memory
    config: {}

http:
  address: 0.0.0.0:8181
  middleware: [ "gzip", "static", "websockets" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  pool:
    num_workers: 1
    supervisor:
      max_worker_memory: 100

kv:
  local:
    driver: memory
    config:
      interval: 60

reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      dirs: [ "." ]
      recursive: true
      ignore: [ "vendor", "runtime" ]
      patterns: [ ".php" ]