version: '3.4'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        VARIANT: "8"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    user: vscode
    command: "tail -f /dev/null"
  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: arena-user
      MYSQL_PASSWORD: arena-password
      MYSQL_DATABASE: arena
