<?php
$this->headLink()
    ->prependStylesheet('/assets/vendor/bootstrap/dist/css/bootstrap.min.css');
$this->inlineScript()
    ->prependFile('/assets/vendor/bootstrap/dist/js/bootstrap.min.js')
    ->prependFile('/assets/vendor/jquery/dist/jquery.min.js');
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <?= $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <style>
        body {
            padding-top: 70px;
        }

        .app {
            min-height: 100vh;
        }

        .app-footer {
            padding-bottom: 1em;
        }

        .mezzio-green,
        h2 a,
        h2 a:hover {
            color: #009655;
        }

        .navbar-brand {
            padding: 0;
        }

        .navbar-brand img {
            margin: -.5rem 0;
            filter: brightness(0) invert(1);
        }
    </style>
</head>

<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        ARENA
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="<?= $this->url('api.ping') ?>" class="nav-link">
                                Ping Test
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <?= $this->content ?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <p>
                &copy; <?= date('Y') ?> Arena
            </p>
        </div>
    </footer>

    <?= $this->inlineScript() ?>
</body>

</html>